version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - gonative-cc/web
    labels:
      - "T:dependencies"
    groups:
      production-non-breaking:
        patterns:
          - "*"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

      development-non-breaking:
        patterns:
          - "*"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
